HOSTNAME='127.0.0.1'

PORT=3306

USERNAME='root'

PASSWORD='study2580'

DATABASE='zhiliao_course'

DB_URI = f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}?charset=utf8mb4"
SQLALCHEMY_DATABASE_URI=DB_URI
# hgihptfjswehbjij
MAIL_SERVER='smtp.qq.com'
MAIL_USE_SSL=True
MAIL_PORT=465
MAIL_USERNAME='485665225@qq.com'
MAIL_PASSWORD='hgihptfjswehbjij'
MAIL_DEFAULT_SENDER='485665225@qq.com'
SECRET_KEY='DGHJSVHJWMDBDJSB'