"""empty message

Revision ID: 878ce24c5cc1
Revises: 07a54b6d44e2
Create Date: 2024-04-11 12:06:40.497042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878ce24c5cc1'
down_revision = '07a54b6d44e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
